In [2]:
#importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the Dataset
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Convert the "sex" column to a categorical type
dataset['sex']=dataset['sex'].astype('category')

#Convert the categorical values into numerical codes
dataset['sex']=dataset['sex'].cat.codes

In [5]:
dataset

      age  sex     bmi  children smoker      charges
0      19    0  27.900         0    yes  16884.92400
1      18    1  33.770         1     no   1725.55230
2      28    1  33.000         3     no   4449.46200
3      33    1  22.705         0     no  21984.47061
4      32    1  28.880         0     no   3866.85520
...   ...  ...     ...       ...    ...          ...
1333   50    1  30.970         3     no  10600.54830
1334   18    0  31.920         0     no   2205.98080
1335   18    0  36.850         0     no   1629.83350
1336   21    0  25.800         0     no   2007.94500
1337   61    0  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
#Convert the "smoker" column to a categorical type
dataset['smoker']=dataset['smoker'].astype('category')

#Convert the categorical values into numerical codes
dataset['smoker']=dataset['smoker'].cat.codes
dataset

      age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [10]:
#dataset = pd.get_dummies(dataset, drop_first=True)
#dataset = dataset.astype(int)

In [11]:
dataset

      age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [12]:
indep=dataset[['age', 'bmi', 'children','sex', 'smoker']]
dep=dataset[['charges']]

In [13]:
#Splitting into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(indep, dep, test_size=1/3, random_state=0)

In [14]:
#preprocessing
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
#Model Selection - Using GridSearchCV

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse','poisson'], 'max_features': [None,'sqrt','log2'],'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3, n_jobs=-1)

#fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [16]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(x_test)

In [17]:
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test, grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': None, 'splitter': 'random'}: 0.7507548166481172

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009973,0.002092,0.003791,1.163203e-03,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.712978,0.435058,0.767659,0.612373,0.654231,0.636460,0.113602,3
1,0.007779,0.003646,0.002394,7.982733e-04,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.559138,0.600811,0.680222,0.552379,0.599258,0.598362,0.045521,9
2,0.007380,0.001494,0.001995,5.223489e-07,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.269984,0.614201,0.741106,0.355822,0.673373,0.530897,0.184474,23
3,0.006781,0.002631,0.002993,8.917504e-04,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.606768,0.597413,0.656794,0.534621,0.373069,0.553733,0.098333,20
4,0.005785,0.000400,0.002792,7.471947e-04,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.583455,0.450997,0.608644,0.648456,0.682807,0.594872,0.079528,10
5,0.005783,0.002706,0.003192,1.464481e-03,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.606400,0.498911,0.618445,0.549951,0.526553,0.560052,0.045870,19
6,0.045702,0.006358,0.002395,7.980348e-04,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.637337,0.579353,0.684880,0.586234,0.630786,0.623718,0.038339,7
7,0.025132,0.003753,0.001996,1.076850e-06,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.668573,0.633181,0.660313,0.672217,0.632468,0.653350,0.017199,1
8,0.019746,0.002130,0.004588,2.326745e-03,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.313627,0.686980,0.531383,0.676363,0.540754,0.549821,0.134934,21
9,0.016553,0.001198,0.002394,4.875288e-04,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.581496,0.319420,0.718986,0.460380,0.597769,0.535610,0.135642,22
10,0.021937,0.005714,0.002195,4.006863e-04,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.569034,0.557715,0.542993,0.665482,0.600561,0.587157,0.043498,13
11,0.015559,0.001848,0.003192,9.765452e-04,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.527930,0.609536,0.612875,0.621955,0.622431,0.598946,0.035862,8
12,0.006581,0.000489,0.002394,4.895129e-04,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.706998,0.470909,0.762288,0.633098,0.668101,0.648279,0.098519,2
13,0.005984,0.000892,0.002395,7.977487e-04,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.645025,0.573481,0.688583,0.610329,0.643127,0.632109,0.038443,4
14,0.006383,0.000798,0.002394,4.887342e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.540825,0.575075,0.655109,0.483533,0.653416,0.581592,0.066156,14
15,0.005385,0.001352,0.002794,7.460106e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.603734,0.477762,0.621695,0.278375,0.594343,0.515182,0.128787,24
16,0.004787,0.000977,0.002396,7.964637e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.465216,0.528796,0.675796,0.624801,0.590482,0.577018,0.073548,15
17,0.004588,0.000799,0.002393,4.871573e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.613963,0.578621,0.603894,0.418198,0.593798,0.561695,0.072693,18
18,0.011169,0.005442,0.003392,1.196401e-03,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.686217,0.397747,0.697016,0.564943,0.621791,0.593543,0.108855,12
19,0.008775,0.006096,0.002993,1.545696e-03,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.665255,0.633502,0.648810,0.593325,0.614018,0.630982,0.025317,5
20,0.008577,0.003373,0.002195,3.996615e-04,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.644787,0.522823,0.645090,0.701478,0.634387,0.629713,0.058414,6
21,0.006582,0.001620,0.002595,7.977010e-04,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.572697,0.660927,0.600525,0.465781,0.530331,0.566052,0.065672,17
22,0.007181,0.000747,0.002193,3.981121e-04,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.449770,0.629250,0.673417,0.630392,0.588784,0.594323,0.077075,11
23,0.005186,0.000981,0.002592,4.919187e-04,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.537533,0.542491,0.643493,0.519093,0.600032,0.568528,0.046249,16

In [20]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 34
BMI: 23
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 2

In [21]:
Future_Prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46151.1245]